name: RGDeployment
on:
 workflow_dispatch:
 push:
   branches:
     - main
jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    environment:
         name: Dev
    name: 'rg-job-name'
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.MVP_SUBSCRIPTION }}
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Apply
        run: terraform apply --auto-approve
        
