name: RGDeployment
on:
 workflow_dispatch:
jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Azure
        uses: azure/login@v1.4
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true 
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
          registry: ${{ secrets.AZURE_REGISTRY_NAMEA }}.azurecr.io
      - name: Build Docker image
        run: |
           docker build -t ${{ secrets.AZURE_REGISTRY_NAMEA }}.azurecr.io/helloapp:${{ github.sha }} .
      - name: Push Docker image to ACR
        run: |
            docker push ${{ secrets.AZURE_REGISTRY_NAMEA }}.azurecr.io/helloapp:${{ github.sha }}

           
          
