name: HelmARCAKSPractice
on:
 workflow_dispatch:
jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: helmtestacr.azurecr.io
          username: helmtestacr
          password: P6XQg4wpsH70PXaiNndEFvfTIf7eh51BR/Qx+aNZwa+ACRAw85ci
      - name: Build Docker image
        run: |
           docker build . -t helmtestacr.azurecr.io/helloapp:${{ github.sha }}
      - name: Push Docker image to ACR
        run: |
            docker push helmtestacr.azurecr.io/helloapp:${{ github.sha }}

           
          
