name: secret rotation POC
on:
 workflow_dispatch:
 issues:
  types:
   - opened
permissions:
 contents: write
 issues: write
 
jobs:
 getcli:
  runs-on: ubuntu-latest
  steps:
    - name: use github cli
      run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}

    - name: update github secret
      run: gh secret set $ENV_SECRET_NAME --body $NEW_SECRET --env $ENVIRONMENT 

            echo "✅ GitHub environment secret updated." 
      env:
        NEW_SECRET: "AM NEW"
        ENVIRONMENT: Dev
        GH_TOKEN: ${{ secrets.GITHUB_TOKE
        ENV_SECRET_NAME: SECRET_TO_UPDATE
