name: secret rotation POC
on:
 workflow_dispatch:
 issues:
  types:
   - opened
permissions:
 contents: write
 
jobs:
 getcli:
  runs-on: ubuntu-latest
  steps:
    - name: use github cli
      run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}
