name: secret rotation POC

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment secret using PAT
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}           # 👈 This must be a valid Personal Access Token
          NEW_SECRET: "AM NEW"
          ENV_SECRET_NAME: SECRET_TO_UPDATE
          ENVIRONMENT: Dev
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh secret set "$ENV_SECRET_NAME" --body "$NEW_SECRET" --env "$ENVIRONMENT"
          echo "✅ GitHub environment secret updated."
