name: secret rotation POC

on:
  workflow_dispatch:
  issues:
    types:
      - opened

permissions:
  contents: write
  issues: write
  actions: write
  security-events: write

jobs:
  getcli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update GitHub environment secret
        env:
          GH_TOKEN: ${{ secrets.PAT }} # Needed for auth
          NEW_SECRET: "AM NEW"
          ENVIRONMENT: Dev
          ENV_SECRET_NAME: REPO_SECRET_TO_UPDATE
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          gh secret set "$ENV_SECRET_NAME" --body "$NEW_SECRET" --env "$ENVIRONMENT"
          echo "✅ GitHub environment secret updated."
          #echo ${{secrets.REPO_SECRET_TO_UPDATE}} | sed 's/./& /g'
